### ISSUE TITLE
Support for GZIPed uploads

### ISSUE THREAD

**Issue by alessandro-tucci-visiontech** [zoomoid/strapi-provider-upload-aws-s3-advanced#20]
**Is your feature request related to a problem? Please describe.**
Unfortunately, GZIPed uploads on S3 buckets are still a useful feature. Indeed, although static objects on S3 are often delivered via Cloudfront, and although Cloudfront supports the on-the-fly compression of served objects, such a compression is often skipped by the CDN itself (maybe for load mitigation policies), leading to uncompressed streams between the browser and the CDN endpoint and performance drops.
More generally, relying on the CDN-side compression is a good choice, but such a feature cannot be taken as granted. As a consequence, it would be useful to let users decide whether to pre-compress their files or not before uploading them to a S3 bucket.

**Describe the solution you'd like**
Such a GZIP compression feature could be added to the provider options. Something like:
`gzip: true | false`
The GZIP compression might be performed by relying on a super-popular, well supported 3rd-party library. [Pako](https://www.npmjs.com/package/pako) seems to be the optimal choice. The `uploadParams` passed to the `putObject` method would be augmented with `ContentEncoding: "gzip"`.

**Describe alternatives you've considered**

**Additional context**

**Comment by zoomoid** [comment]
I'm not a big fan of adding dependencies inside a plugin, so I'd refrain from implementing this. You seem to want both at-rest and in-flight compression. I can't make any assumptions as to your primary content types, but considering that we used strapi mostly for media data that was already heavily compressed, the trade-off between reduction in size and computation hardly seems worth it to me at least. 

At least in the plugin's code, I don't see a good reason to enable or disable compression altogether. You already said that Cloudfront (or other CDNs) support ad-hoc inflight compression, and as a suggestion, I would attempt to implement content-dependent compression at rest using tooling provided by your cloud provider, e.g., S3 object lambdas. 

Seeing that this issue is already well over a year old, and I'm no longer working with and around strapi, I'm going to close this issue. If you still need this, forking is always an option :)

**Comment by zoomoid** [comment]
I'm not a big fan of adding dependencies inside a plugin, so I'd refrain from implementing this. You seem to want both at-rest and in-flight compression. I can't make any assumptions as to your primary content types, but considering that we used strapi mostly for media data that was already heavily compressed, the trade-off between reduction in size and computation hardly seems worth it to me at least. 

At least in the plugin's code, I don't see a good reason to enable or disable compression altogether. You already said that Cloudfront (or other CDNs) support ad-hoc inflight compression, and as a suggestion, I would attempt to implement content-dependent compression at rest using tooling provided by your cloud provider, e.g., S3 object lambdas. 

Seeing that this issue is already well over a year old, and I'm no longer working with and around strapi, I'm going to close this issue. If you still need this, forking is always an option :)
